// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyqajxbkxiddfqnzkcmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cWFqeGJreGlkZGZxbnprY21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyOTI5MzcsImV4cCI6MjA4MTg2ODkzN30.TOFFCHAOPiRK4bE-6d07ubXVv5FS15ZXcfKhpr3m-6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});